stock_companies = [
    {"company": "Apple Inc.", "symbol": "AAPL"},
    {"company": "Microsoft Corporation", "symbol": "MSFT"},
    {"company": "Alphabet Inc. (Class A)", "symbol": "GOOGL"},
    {"company": "Alphabet Inc. (Class C)", "symbol": "GOOG"},
    {"company": "Amazon.com Inc.", "symbol": "AMZN"},
    {"company": "Facebook, Inc.", "symbol": "FB"},
    {"company": "Tesla, Inc.", "symbol": "TSLA"},
    {"company": "JPMorgan Chase & Co.", "symbol": "JPM"},
    {"company": "Johnson & Johnson", "symbol": "JNJ"},
    {"company": "Procter & Gamble Co.", "symbol": "PG"},
    {"company": "The Coca-Cola Company", "symbol": "KO"},
    {"company": "Intel Corporation", "symbol": "INTC"},
    {"company": "Walt Disney Company", "symbol": "DIS"},
    {"company": "IBM (International Business Machines Corporation)", "symbol": "IBM"},
    {"company": "Netflix, Inc.", "symbol": "NFLX"},
    {"company": "Visa Inc.", "symbol": "V"},
    {"company": "Walmart Inc.", "symbol": "WMT"},
]